<?php


namespace frontend\widgets\cms;


class FiveWidget extends WeshopBlockWidget
{

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        echo $this->render('five');
    }
}