<?php


namespace frontend\widgets\cms;


class SevenWidget extends WeshopBlockWidget
{

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        echo $this->render('seven', ['block' => $this->block]);
    }
}