<?php


namespace frontend\widgets\cms;


class SevenWidget extends WeshopBlockWidget
{

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $categories = $this->block['categories'] ? $this->block['categories'] : [];
        $products = $this->block['products'] ? $this->block['products'] : [];
        $images = isset($this->block['images']) ? $this->block['images'] : [];
        $keywords = isset($this->block['keywords']) ? $this->block['keywords'] : '';
        return $this->render('seven', [
            'block' => $this->block['block'],
            'categories' => $categories,
            'products' => $products,
            'images' => $images,
            'keywords' => $keywords
        ]);
    }
}