<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/courier.proto

namespace Courier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Courier.CourierCalculateVas</code>
 */
class CourierCalculateVas extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double cod = 1;</code>
     */
    private $cod = 0.0;
    /**
     * Generated from protobuf field <code>double insurance = 2;</code>
     */
    private $insurance = 0.0;
    /**
     * Generated from protobuf field <code>double checking = 3;</code>
     */
    private $checking = 0.0;
    /**
     * Generated from protobuf field <code>double remote = 4;</code>
     */
    private $remote = 0.0;
    /**
     * Generated from protobuf field <code>double customs = 5;</code>
     */
    private $customs = 0.0;
    /**
     * Generated from protobuf field <code>double line_haul = 6;</code>
     */
    private $line_haul = 0.0;
    /**
     * Generated from protobuf field <code>double tracking = 7;</code>
     */
    private $tracking = 0.0;
    /**
     * Generated from protobuf field <code>double pod = 8;</code>
     */
    private $pod = 0.0;
    /**
     * Generated from protobuf field <code>double restrict = 9;</code>
     */
    private $restrict = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $cod
     *     @type float $insurance
     *     @type float $checking
     *     @type float $remote
     *     @type float $customs
     *     @type float $line_haul
     *     @type float $tracking
     *     @type float $pod
     *     @type float $restrict
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Courier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double cod = 1;</code>
     * @return float
     */
    public function getCod()
    {
        return $this->cod;
    }

    /**
     * Generated from protobuf field <code>double cod = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setCod($var)
    {
        GPBUtil::checkDouble($var);
        $this->cod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double insurance = 2;</code>
     * @return float
     */
    public function getInsurance()
    {
        return $this->insurance;
    }

    /**
     * Generated from protobuf field <code>double insurance = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setInsurance($var)
    {
        GPBUtil::checkDouble($var);
        $this->insurance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double checking = 3;</code>
     * @return float
     */
    public function getChecking()
    {
        return $this->checking;
    }

    /**
     * Generated from protobuf field <code>double checking = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setChecking($var)
    {
        GPBUtil::checkDouble($var);
        $this->checking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double remote = 4;</code>
     * @return float
     */
    public function getRemote()
    {
        return $this->remote;
    }

    /**
     * Generated from protobuf field <code>double remote = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setRemote($var)
    {
        GPBUtil::checkDouble($var);
        $this->remote = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double customs = 5;</code>
     * @return float
     */
    public function getCustoms()
    {
        return $this->customs;
    }

    /**
     * Generated from protobuf field <code>double customs = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCustoms($var)
    {
        GPBUtil::checkDouble($var);
        $this->customs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double line_haul = 6;</code>
     * @return float
     */
    public function getLineHaul()
    {
        return $this->line_haul;
    }

    /**
     * Generated from protobuf field <code>double line_haul = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setLineHaul($var)
    {
        GPBUtil::checkDouble($var);
        $this->line_haul = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tracking = 7;</code>
     * @return float
     */
    public function getTracking()
    {
        return $this->tracking;
    }

    /**
     * Generated from protobuf field <code>double tracking = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTracking($var)
    {
        GPBUtil::checkDouble($var);
        $this->tracking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double pod = 8;</code>
     * @return float
     */
    public function getPod()
    {
        return $this->pod;
    }

    /**
     * Generated from protobuf field <code>double pod = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setPod($var)
    {
        GPBUtil::checkDouble($var);
        $this->pod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double restrict = 9;</code>
     * @return float
     */
    public function getRestrict()
    {
        return $this->restrict;
    }

    /**
     * Generated from protobuf field <code>double restrict = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setRestrict($var)
    {
        GPBUtil::checkDouble($var);
        $this->restrict = $var;

        return $this;
    }

}

