<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/courier.proto

namespace Courier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Courier.CourierCalculate</code>
 */
class CourierCalculate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string courier_logo = 1;</code>
     */
    private $courier_logo = '';
    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     */
    private $service_name = '';
    /**
     * Generated from protobuf field <code>int32 courier_id = 3;</code>
     */
    private $courier_id = 0;
    /**
     * Generated from protobuf field <code>string dropoff_point = 4;</code>
     */
    private $dropoff_point = '';
    /**
     * Generated from protobuf field <code>double duty = 5;</code>
     */
    private $duty = 0.0;
    /**
     * Generated from protobuf field <code>double shipping_fee = 6;</code>
     */
    private $shipping_fee = 0.0;
    /**
     * Generated from protobuf field <code>double discount = 7;</code>
     */
    private $discount = 0.0;
    /**
     * Generated from protobuf field <code>string handover_options = 8;</code>
     */
    private $handover_options = '';
    /**
     * Generated from protobuf field <code>string currency = 9;</code>
     */
    private $currency = '';
    /**
     * Generated from protobuf field <code>.Courier.CourierCalculateVas vas = 10;</code>
     */
    private $vas = null;
    /**
     * Generated from protobuf field <code>string insurance_policy = 11;</code>
     */
    private $insurance_policy = '';
    /**
     * Generated from protobuf field <code>int32 delivery_time_rank = 12;</code>
     */
    private $delivery_time_rank = 0;
    /**
     * Generated from protobuf field <code>int32 fee_rank = 13;</code>
     */
    private $fee_rank = 0;
    /**
     * Generated from protobuf field <code>string courier_name = 14;</code>
     */
    private $courier_name = '';
    /**
     * Generated from protobuf field <code>string service_code = 15;</code>
     */
    private $service_code = '';
    /**
     * Generated from protobuf field <code>double rating = 16;</code>
     */
    private $rating = 0.0;
    /**
     * Generated from protobuf field <code>double total_fee = 17;</code>
     */
    private $total_fee = 0.0;
    /**
     * Generated from protobuf field <code>double tax = 18;</code>
     */
    private $tax = 0.0;
    /**
     * Generated from protobuf field <code>double min_delivery_time = 20;</code>
     */
    private $min_delivery_time = 0.0;
    /**
     * Generated from protobuf field <code>double max_delivery_time = 21;</code>
     */
    private $max_delivery_time = 0.0;
    /**
     * Generated from protobuf field <code>string handover_policy = 22;</code>
     */
    private $handover_policy = '';
    /**
     * Generated from protobuf field <code>double cod_value = 23;</code>
     */
    private $cod_value = 0.0;
    /**
     * Generated from protobuf field <code>.Courier.FulfillmentFee fulfillment = 24;</code>
     */
    private $fulfillment = null;
    /**
     * Generated from protobuf field <code>.Courier.CourierCalculateDiscountDetail discount_detail = 25;</code>
     */
    private $discount_detail = null;
    /**
     * Generated from protobuf field <code>double return_fee = 26;</code>
     */
    private $return_fee = 0.0;
    /**
     * Generated from protobuf field <code>double chargeable_weight = 27;</code>
     */
    private $chargeable_weight = 0.0;
    /**
     * Generated from protobuf field <code>int32 service_id = 28;</code>
     */
    private $service_id = 0;
    /**
     * Generated from protobuf field <code>string sorting_hub = 29;</code>
     */
    private $sorting_hub = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $courier_logo
     *     @type string $service_name
     *     @type int $courier_id
     *     @type string $dropoff_point
     *     @type float $duty
     *     @type float $shipping_fee
     *     @type float $discount
     *     @type string $handover_options
     *     @type string $currency
     *     @type \Courier\CourierCalculateVas $vas
     *     @type string $insurance_policy
     *     @type int $delivery_time_rank
     *     @type int $fee_rank
     *     @type string $courier_name
     *     @type string $service_code
     *     @type float $rating
     *     @type float $total_fee
     *     @type float $tax
     *     @type float $min_delivery_time
     *     @type float $max_delivery_time
     *     @type string $handover_policy
     *     @type float $cod_value
     *     @type \Courier\FulfillmentFee $fulfillment
     *     @type \Courier\CourierCalculateDiscountDetail $discount_detail
     *     @type float $return_fee
     *     @type float $chargeable_weight
     *     @type int $service_id
     *     @type string $sorting_hub
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Courier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string courier_logo = 1;</code>
     * @return string
     */
    public function getCourierLogo()
    {
        return $this->courier_logo;
    }

    /**
     * Generated from protobuf field <code>string courier_logo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCourierLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->courier_logo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 courier_id = 3;</code>
     * @return int
     */
    public function getCourierId()
    {
        return $this->courier_id;
    }

    /**
     * Generated from protobuf field <code>int32 courier_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCourierId($var)
    {
        GPBUtil::checkInt32($var);
        $this->courier_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dropoff_point = 4;</code>
     * @return string
     */
    public function getDropoffPoint()
    {
        return $this->dropoff_point;
    }

    /**
     * Generated from protobuf field <code>string dropoff_point = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDropoffPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->dropoff_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double duty = 5;</code>
     * @return float
     */
    public function getDuty()
    {
        return $this->duty;
    }

    /**
     * Generated from protobuf field <code>double duty = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDuty($var)
    {
        GPBUtil::checkDouble($var);
        $this->duty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double shipping_fee = 6;</code>
     * @return float
     */
    public function getShippingFee()
    {
        return $this->shipping_fee;
    }

    /**
     * Generated from protobuf field <code>double shipping_fee = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setShippingFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double discount = 7;</code>
     * @return float
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Generated from protobuf field <code>double discount = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkDouble($var);
        $this->discount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string handover_options = 8;</code>
     * @return string
     */
    public function getHandoverOptions()
    {
        return $this->handover_options;
    }

    /**
     * Generated from protobuf field <code>string handover_options = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHandoverOptions($var)
    {
        GPBUtil::checkString($var, True);
        $this->handover_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 9;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Courier.CourierCalculateVas vas = 10;</code>
     * @return \Courier\CourierCalculateVas
     */
    public function getVas()
    {
        return $this->vas;
    }

    /**
     * Generated from protobuf field <code>.Courier.CourierCalculateVas vas = 10;</code>
     * @param \Courier\CourierCalculateVas $var
     * @return $this
     */
    public function setVas($var)
    {
        GPBUtil::checkMessage($var, \Courier\CourierCalculateVas::class);
        $this->vas = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string insurance_policy = 11;</code>
     * @return string
     */
    public function getInsurancePolicy()
    {
        return $this->insurance_policy;
    }

    /**
     * Generated from protobuf field <code>string insurance_policy = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setInsurancePolicy($var)
    {
        GPBUtil::checkString($var, True);
        $this->insurance_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 delivery_time_rank = 12;</code>
     * @return int
     */
    public function getDeliveryTimeRank()
    {
        return $this->delivery_time_rank;
    }

    /**
     * Generated from protobuf field <code>int32 delivery_time_rank = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setDeliveryTimeRank($var)
    {
        GPBUtil::checkInt32($var);
        $this->delivery_time_rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fee_rank = 13;</code>
     * @return int
     */
    public function getFeeRank()
    {
        return $this->fee_rank;
    }

    /**
     * Generated from protobuf field <code>int32 fee_rank = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setFeeRank($var)
    {
        GPBUtil::checkInt32($var);
        $this->fee_rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string courier_name = 14;</code>
     * @return string
     */
    public function getCourierName()
    {
        return $this->courier_name;
    }

    /**
     * Generated from protobuf field <code>string courier_name = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setCourierName($var)
    {
        GPBUtil::checkString($var, True);
        $this->courier_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_code = 15;</code>
     * @return string
     */
    public function getServiceCode()
    {
        return $this->service_code;
    }

    /**
     * Generated from protobuf field <code>string service_code = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rating = 16;</code>
     * @return float
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Generated from protobuf field <code>double rating = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setRating($var)
    {
        GPBUtil::checkDouble($var);
        $this->rating = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_fee = 17;</code>
     * @return float
     */
    public function getTotalFee()
    {
        return $this->total_fee;
    }

    /**
     * Generated from protobuf field <code>double total_fee = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tax = 18;</code>
     * @return float
     */
    public function getTax()
    {
        return $this->tax;
    }

    /**
     * Generated from protobuf field <code>double tax = 18;</code>
     * @param float $var
     * @return $this
     */
    public function setTax($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double min_delivery_time = 20;</code>
     * @return float
     */
    public function getMinDeliveryTime()
    {
        return $this->min_delivery_time;
    }

    /**
     * Generated from protobuf field <code>double min_delivery_time = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setMinDeliveryTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->min_delivery_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double max_delivery_time = 21;</code>
     * @return float
     */
    public function getMaxDeliveryTime()
    {
        return $this->max_delivery_time;
    }

    /**
     * Generated from protobuf field <code>double max_delivery_time = 21;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxDeliveryTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->max_delivery_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string handover_policy = 22;</code>
     * @return string
     */
    public function getHandoverPolicy()
    {
        return $this->handover_policy;
    }

    /**
     * Generated from protobuf field <code>string handover_policy = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setHandoverPolicy($var)
    {
        GPBUtil::checkString($var, True);
        $this->handover_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double cod_value = 23;</code>
     * @return float
     */
    public function getCodValue()
    {
        return $this->cod_value;
    }

    /**
     * Generated from protobuf field <code>double cod_value = 23;</code>
     * @param float $var
     * @return $this
     */
    public function setCodValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->cod_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Courier.FulfillmentFee fulfillment = 24;</code>
     * @return \Courier\FulfillmentFee
     */
    public function getFulfillment()
    {
        return $this->fulfillment;
    }

    /**
     * Generated from protobuf field <code>.Courier.FulfillmentFee fulfillment = 24;</code>
     * @param \Courier\FulfillmentFee $var
     * @return $this
     */
    public function setFulfillment($var)
    {
        GPBUtil::checkMessage($var, \Courier\FulfillmentFee::class);
        $this->fulfillment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Courier.CourierCalculateDiscountDetail discount_detail = 25;</code>
     * @return \Courier\CourierCalculateDiscountDetail
     */
    public function getDiscountDetail()
    {
        return $this->discount_detail;
    }

    /**
     * Generated from protobuf field <code>.Courier.CourierCalculateDiscountDetail discount_detail = 25;</code>
     * @param \Courier\CourierCalculateDiscountDetail $var
     * @return $this
     */
    public function setDiscountDetail($var)
    {
        GPBUtil::checkMessage($var, \Courier\CourierCalculateDiscountDetail::class);
        $this->discount_detail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double return_fee = 26;</code>
     * @return float
     */
    public function getReturnFee()
    {
        return $this->return_fee;
    }

    /**
     * Generated from protobuf field <code>double return_fee = 26;</code>
     * @param float $var
     * @return $this
     */
    public function setReturnFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->return_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double chargeable_weight = 27;</code>
     * @return float
     */
    public function getChargeableWeight()
    {
        return $this->chargeable_weight;
    }

    /**
     * Generated from protobuf field <code>double chargeable_weight = 27;</code>
     * @param float $var
     * @return $this
     */
    public function setChargeableWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->chargeable_weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 service_id = 28;</code>
     * @return int
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Generated from protobuf field <code>int32 service_id = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkInt32($var);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sorting_hub = 29;</code>
     * @return string
     */
    public function getSortingHub()
    {
        return $this->sorting_hub;
    }

    /**
     * Generated from protobuf field <code>string sorting_hub = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setSortingHub($var)
    {
        GPBUtil::checkString($var, True);
        $this->sorting_hub = $var;

        return $this;
    }

}

