<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/courier.proto

namespace Courier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Courier.CreateOrderResultFee</code>
 */
class CreateOrderResultFee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double cod_fee = 1;</code>
     */
    private $cod_fee = 0.0;
    /**
     * Generated from protobuf field <code>double shipping_fee = 2;</code>
     */
    private $shipping_fee = 0.0;
    /**
     * Generated from protobuf field <code>double insurance_fee = 3;</code>
     */
    private $insurance_fee = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $cod_fee
     *     @type float $shipping_fee
     *     @type float $insurance_fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Courier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double cod_fee = 1;</code>
     * @return float
     */
    public function getCodFee()
    {
        return $this->cod_fee;
    }

    /**
     * Generated from protobuf field <code>double cod_fee = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setCodFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->cod_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double shipping_fee = 2;</code>
     * @return float
     */
    public function getShippingFee()
    {
        return $this->shipping_fee;
    }

    /**
     * Generated from protobuf field <code>double shipping_fee = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setShippingFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->shipping_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double insurance_fee = 3;</code>
     * @return float
     */
    public function getInsuranceFee()
    {
        return $this->insurance_fee;
    }

    /**
     * Generated from protobuf field <code>double insurance_fee = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setInsuranceFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->insurance_fee = $var;

        return $this;
    }

}

