<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/courier.proto

namespace Courier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Courier.CreateOrderResponse</code>
 */
class CreateOrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     */
    private $Error = false;
    /**
     * Generated from protobuf field <code>string ErrorCode = 2;</code>
     */
    private $ErrorCode = '';
    /**
     * Generated from protobuf field <code>string ErrorMessage = 3;</code>
     */
    private $ErrorMessage = '';
    /**
     * Generated from protobuf field <code>.Courier.CreateOrderResult Data = 4;</code>
     */
    private $Data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Error
     *     @type string $ErrorCode
     *     @type string $ErrorMessage
     *     @type \Courier\CreateOrderResult $Data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Courier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     * @return bool
     */
    public function getError()
    {
        return $this->Error;
    }

    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkBool($var);
        $this->Error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ErrorCode = 2;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->ErrorCode;
    }

    /**
     * Generated from protobuf field <code>string ErrorCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ErrorMessage = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->ErrorMessage;
    }

    /**
     * Generated from protobuf field <code>string ErrorMessage = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Courier.CreateOrderResult Data = 4;</code>
     * @return \Courier\CreateOrderResult
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>.Courier.CreateOrderResult Data = 4;</code>
     * @param \Courier\CreateOrderResult $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Courier\CreateOrderResult::class);
        $this->Data = $var;

        return $this;
    }

}

