<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/courier.proto

namespace Courier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Courier.CreateOrderResult</code>
 */
class CreateOrderResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string label_url = 1;</code>
     */
    private $label_url = '';
    /**
     * Generated from protobuf field <code>.Courier.CreateOrderResultFee fee = 2;</code>
     */
    private $fee = null;
    /**
     * Generated from protobuf field <code>string tracking_number = 3;</code>
     */
    private $tracking_number = '';
    /**
     * Generated from protobuf field <code>double cod_value = 4;</code>
     */
    private $cod_value = 0.0;
    /**
     * Generated from protobuf field <code>string service_code = 5;</code>
     */
    private $service_code = '';
    /**
     * Generated from protobuf field <code>int32 service_id = 6;</code>
     */
    private $service_id = 0;
    /**
     * Generated from protobuf field <code>int32 courier_id = 7;</code>
     */
    private $courier_id = 0;
    /**
     * Generated from protobuf field <code>double min_delivery_time = 8;</code>
     */
    private $min_delivery_time = 0.0;
    /**
     * Generated from protobuf field <code>double max_delivery_time = 9;</code>
     */
    private $max_delivery_time = 0.0;
    /**
     * Generated from protobuf field <code>double money_collect = 10;</code>
     */
    private $money_collect = 0.0;
    /**
     * Generated from protobuf field <code>double total_fee = 11;</code>
     */
    private $total_fee = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $label_url
     *     @type \Courier\CreateOrderResultFee $fee
     *     @type string $tracking_number
     *     @type float $cod_value
     *     @type string $service_code
     *     @type int $service_id
     *     @type int $courier_id
     *     @type float $min_delivery_time
     *     @type float $max_delivery_time
     *     @type float $money_collect
     *     @type float $total_fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Courier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string label_url = 1;</code>
     * @return string
     */
    public function getLabelUrl()
    {
        return $this->label_url;
    }

    /**
     * Generated from protobuf field <code>string label_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->label_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Courier.CreateOrderResultFee fee = 2;</code>
     * @return \Courier\CreateOrderResultFee
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>.Courier.CreateOrderResultFee fee = 2;</code>
     * @param \Courier\CreateOrderResultFee $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkMessage($var, \Courier\CreateOrderResultFee::class);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 3;</code>
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->tracking_number;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double cod_value = 4;</code>
     * @return float
     */
    public function getCodValue()
    {
        return $this->cod_value;
    }

    /**
     * Generated from protobuf field <code>double cod_value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setCodValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->cod_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_code = 5;</code>
     * @return string
     */
    public function getServiceCode()
    {
        return $this->service_code;
    }

    /**
     * Generated from protobuf field <code>string service_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 service_id = 6;</code>
     * @return int
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Generated from protobuf field <code>int32 service_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkInt32($var);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 courier_id = 7;</code>
     * @return int
     */
    public function getCourierId()
    {
        return $this->courier_id;
    }

    /**
     * Generated from protobuf field <code>int32 courier_id = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCourierId($var)
    {
        GPBUtil::checkInt32($var);
        $this->courier_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double min_delivery_time = 8;</code>
     * @return float
     */
    public function getMinDeliveryTime()
    {
        return $this->min_delivery_time;
    }

    /**
     * Generated from protobuf field <code>double min_delivery_time = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setMinDeliveryTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->min_delivery_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double max_delivery_time = 9;</code>
     * @return float
     */
    public function getMaxDeliveryTime()
    {
        return $this->max_delivery_time;
    }

    /**
     * Generated from protobuf field <code>double max_delivery_time = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxDeliveryTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->max_delivery_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double money_collect = 10;</code>
     * @return float
     */
    public function getMoneyCollect()
    {
        return $this->money_collect;
    }

    /**
     * Generated from protobuf field <code>double money_collect = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setMoneyCollect($var)
    {
        GPBUtil::checkDouble($var);
        $this->money_collect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_fee = 11;</code>
     * @return float
     */
    public function getTotalFee()
    {
        return $this->total_fee;
    }

    /**
     * Generated from protobuf field <code>double total_fee = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_fee = $var;

        return $this;
    }

}

