<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/courier.proto

namespace Courier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Courier.FulfillmentFee</code>
 */
class FulfillmentFee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double handling = 1;</code>
     */
    private $handling = 0.0;
    /**
     * Generated from protobuf field <code>double material = 2;</code>
     */
    private $material = 0.0;
    /**
     * Generated from protobuf field <code>double special = 3;</code>
     */
    private $special = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $handling
     *     @type float $material
     *     @type float $special
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Courier::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double handling = 1;</code>
     * @return float
     */
    public function getHandling()
    {
        return $this->handling;
    }

    /**
     * Generated from protobuf field <code>double handling = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setHandling($var)
    {
        GPBUtil::checkDouble($var);
        $this->handling = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double material = 2;</code>
     * @return float
     */
    public function getMaterial()
    {
        return $this->material;
    }

    /**
     * Generated from protobuf field <code>double material = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMaterial($var)
    {
        GPBUtil::checkDouble($var);
        $this->material = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double special = 3;</code>
     * @return float
     */
    public function getSpecial()
    {
        return $this->special;
    }

    /**
     * Generated from protobuf field <code>double special = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setSpecial($var)
    {
        GPBUtil::checkDouble($var);
        $this->special = $var;

        return $this;
    }

}

