<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accounting.proto

namespace Accouting;

/**
 * Protobuf type <code>Accouting.Accouting</code>
 */
interface AccoutingInterface
{
    /**
     *&#47; TAO SO DU  CREATE - MERCHANT
     *
     * Method <code>createMerchantById</code>
     *
     * @param \Accouting\CreateMerchantByIdRequest $request
     * @return \Accouting\ReponseCreateMerchantById
     */
    public function createMerchantById(\Accouting\CreateMerchantByIdRequest $request);

    /**
     * LAY THONG TIN SO DU - GET MERCHANT
     *
     * Method <code>getListMerchantById</code>
     *
     * @param \Accouting\GetListMerchantByIdRequest $request
     * @return \Accouting\GetListMerchantByIdResponse
     */
    public function getListMerchantById(\Accouting\GetListMerchantByIdRequest $request);

    /**
     * TAO GIAO DICH ( CREATE TRANSACTION)
     *
     * Method <code>wsCreateTransaction</code>
     *
     * @param \Accouting\WsCreateTransactionRequest $request
     * @return \Accouting\WsCreateTransactionResponse
     */
    public function wsCreateTransaction(\Accouting\WsCreateTransactionRequest $request);

}

