<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accounting.proto

namespace Accouting;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Accouting.CreateMerchantByIdRequest</code>
 */
class CreateMerchantByIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * MA QUOC GIA (VN,TH,MY,ID)
     *
     * Generated from protobuf field <code>string CountryCode = 1;</code>
     */
    private $CountryCode = '';
    /**
     * USER_ID
     *
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     */
    private $UserId = 0;
    /**
     * MA TIEN THEO QUOC GIA (VN: VND,MY:MYR , ID:IDR, TH:THB)
     *
     * Generated from protobuf field <code>string CurrencyCode = 3;</code>
     */
    private $CurrencyCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CountryCode
     *           MA QUOC GIA (VN,TH,MY,ID)
     *     @type int $UserId
     *           USER_ID
     *     @type string $CurrencyCode
     *           MA TIEN THEO QUOC GIA (VN: VND,MY:MYR , ID:IDR, TH:THB)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Accounting::initOnce();
        parent::__construct($data);
    }

    /**
     * MA QUOC GIA (VN,TH,MY,ID)
     *
     * Generated from protobuf field <code>string CountryCode = 1;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->CountryCode;
    }

    /**
     * MA QUOC GIA (VN,TH,MY,ID)
     *
     * Generated from protobuf field <code>string CountryCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->CountryCode = $var;

        return $this;
    }

    /**
     * USER_ID
     *
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * USER_ID
     *
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->UserId = $var;

        return $this;
    }

    /**
     * MA TIEN THEO QUOC GIA (VN: VND,MY:MYR , ID:IDR, TH:THB)
     *
     * Generated from protobuf field <code>string CurrencyCode = 3;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->CurrencyCode;
    }

    /**
     * MA TIEN THEO QUOC GIA (VN: VND,MY:MYR , ID:IDR, TH:THB)
     *
     * Generated from protobuf field <code>string CurrencyCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->CurrencyCode = $var;

        return $this;
    }

}

