<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accounting.proto

namespace Accouting;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * KHI NAP TIEN => SO TIEN DC NAP SE + VAO SO DU PVC (BalancePvc)
 * NOTE: So du kha dung = so du duyet don   + han muc  - van chuyen tam tinh
 *
 * Generated from protobuf message <code>Accouting.GetListMerchantByIdRequest</code>
 */
class GetListMerchantByIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string CountryCode = 1;</code>
     */
    private $CountryCode = '';
    /**
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     */
    private $UserId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CountryCode
     *     @type int $UserId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Accounting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string CountryCode = 1;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->CountryCode;
    }

    /**
     * Generated from protobuf field <code>string CountryCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->CountryCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->UserId = $var;

        return $this;
    }

}

