<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accounting.proto

namespace Accouting;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Accouting.WsCreateTransactionResponse</code>
 */
class WsCreateTransactionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     */
    private $Error = false;
    /**
     * THONG BAO CHI TIET
     *
     * Generated from protobuf field <code>string Message = 2;</code>
     */
    private $Message = '';
    /**
     * RA VE MA LOI NEU Error = TRUE
     *
     * Generated from protobuf field <code>string ErrorCode = 3;</code>
     */
    private $ErrorCode = '';
    /**
     * CHUOI JSON DUMPS data User
     *
     * Generated from protobuf field <code>string Data = 4;</code>
     */
    private $Data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Error
     *     @type string $Message
     *           THONG BAO CHI TIET
     *     @type string $ErrorCode
     *           RA VE MA LOI NEU Error = TRUE
     *     @type string $Data
     *           CHUOI JSON DUMPS data User
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Accounting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     * @return bool
     */
    public function getError()
    {
        return $this->Error;
    }

    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkBool($var);
        $this->Error = $var;

        return $this;
    }

    /**
     * THONG BAO CHI TIET
     *
     * Generated from protobuf field <code>string Message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * THONG BAO CHI TIET
     *
     * Generated from protobuf field <code>string Message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     * RA VE MA LOI NEU Error = TRUE
     *
     * Generated from protobuf field <code>string ErrorCode = 3;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->ErrorCode;
    }

    /**
     * RA VE MA LOI NEU Error = TRUE
     *
     * Generated from protobuf field <code>string ErrorCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorCode = $var;

        return $this;
    }

    /**
     * CHUOI JSON DUMPS data User
     *
     * Generated from protobuf field <code>string Data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * CHUOI JSON DUMPS data User
     *
     * Generated from protobuf field <code>string Data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->Data = $var;

        return $this;
    }

}

