<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.SignUpResponse</code>
 */
class SignUpResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     */
    private $Error = false;
    /**
     * Generated from protobuf field <code>.user.SignUpUser Data = 2;</code>
     */
    private $Data = null;
    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     */
    private $Message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Error
     *     @type \User\SignUpUser $Data
     *     @type string $Message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     * @return bool
     */
    public function getError()
    {
        return $this->Error;
    }

    /**
     * Generated from protobuf field <code>bool Error = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkBool($var);
        $this->Error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.user.SignUpUser Data = 2;</code>
     * @return \User\SignUpUser
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>.user.SignUpUser Data = 2;</code>
     * @param \User\SignUpUser $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \User\SignUpUser::class);
        $this->Data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

}

