<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>User.SignUpRequest</code>
 */
class SignUpRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string country = 1;</code>
     */
    private $country = '';
    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     */
    private $currency = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>string fullname = 4;</code>
     */
    private $fullname = '';
    /**
     * Generated from protobuf field <code>string password1 = 5;</code>
     */
    private $password1 = '';
    /**
     * Generated from protobuf field <code>string password2 = 6;</code>
     */
    private $password2 = '';
    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     */
    private $phone = '';
    /**
     * NETSALE / WESHOP
     *
     * Generated from protobuf field <code>string platform = 8;</code>
     */
    private $platform = '';
    /**
     * User ID of Weshop
     *
     * Generated from protobuf field <code>int32 platform_user = 9;</code>
     */
    private $platform_user = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $country
     *     @type string $currency
     *     @type string $email
     *     @type string $fullname
     *     @type string $password1
     *     @type string $password2
     *     @type string $phone
     *     @type string $platform
     *           NETSALE / WESHOP
     *     @type int $platform_user
     *           User ID of Weshop
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string country = 1;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fullname = 4;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     * Generated from protobuf field <code>string fullname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password1 = 5;</code>
     * @return string
     */
    public function getPassword1()
    {
        return $this->password1;
    }

    /**
     * Generated from protobuf field <code>string password1 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword1($var)
    {
        GPBUtil::checkString($var, True);
        $this->password1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password2 = 6;</code>
     * @return string
     */
    public function getPassword2()
    {
        return $this->password2;
    }

    /**
     * Generated from protobuf field <code>string password2 = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword2($var)
    {
        GPBUtil::checkString($var, True);
        $this->password2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * NETSALE / WESHOP
     *
     * Generated from protobuf field <code>string platform = 8;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * NETSALE / WESHOP
     *
     * Generated from protobuf field <code>string platform = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * User ID of Weshop
     *
     * Generated from protobuf field <code>int32 platform_user = 9;</code>
     * @return int
     */
    public function getPlatformUser()
    {
        return $this->platform_user;
    }

    /**
     * User ID of Weshop
     *
     * Generated from protobuf field <code>int32 platform_user = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatformUser($var)
    {
        GPBUtil::checkInt32($var);
        $this->platform_user = $var;

        return $this;
    }

}

