<?php


namespace frontend\modules\payment\methods;


class McpayWidget extends MethodWidget
{

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('mc_pay');
    }
}