<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.SignUpUser</code>
 */
class SignUpUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>string email = 2;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>string username = 3;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>string fullname = 4;</code>
     */
    private $fullname = '';
    /**
     * Generated from protobuf field <code>string invite_code = 5;</code>
     */
    private $invite_code = '';
    /**
     * Generated from protobuf field <code>bool is_active = 9;</code>
     */
    private $is_active = false;
    /**
     * Generated from protobuf field <code>int32 created_time = 10;</code>
     */
    private $created_time = 0;
    /**
     * Generated from protobuf field <code>int32 updated_time = 11;</code>
     */
    private $updated_time = 0;
    /**
     * Generated from protobuf field <code>int32 last_login = 12;</code>
     */
    private $last_login = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $user_id
     *     @type string $email
     *     @type string $username
     *     @type string $fullname
     *     @type string $invite_code
     *     @type bool $is_active
     *     @type int $created_time
     *     @type int $updated_time
     *     @type int $last_login
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int32 user_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fullname = 4;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     * Generated from protobuf field <code>string fullname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invite_code = 5;</code>
     * @return string
     */
    public function getInviteCode()
    {
        return $this->invite_code;
    }

    /**
     * Generated from protobuf field <code>string invite_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInviteCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->invite_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 9;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return $this->is_active;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->is_active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_time = 10;</code>
     * @return int
     */
    public function getCreatedTime()
    {
        return $this->created_time;
    }

    /**
     * Generated from protobuf field <code>int32 created_time = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 updated_time = 11;</code>
     * @return int
     */
    public function getUpdatedTime()
    {
        return $this->updated_time;
    }

    /**
     * Generated from protobuf field <code>int32 updated_time = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 last_login = 12;</code>
     * @return int
     */
    public function getLastLogin()
    {
        return $this->last_login;
    }

    /**
     * Generated from protobuf field <code>int32 last_login = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setLastLogin($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_login = $var;

        return $this;
    }

}

