<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-03-01
 * Time: 09:50
 */

namespace weshop\payment\methods;


use Yii;

class VisaMaster extends \weshop\payment\BasePaymentMethod
{

    public function getName()
    {
        return 'VisaMaster';
    }

    public function getNavigator()
    {
        return parent::getNavigator(); // TODO: Change the autogenerated stub
    }

    public function getDetail()
    {
        return Yii::$app->view->render('methods/visa-master/detail');
    }
}