<?php
/**
 * Created by PhpStorm.
 * User: galat
 * Date: 25/02/2019
 * Time: 16:48
 */

namespace common\models;


use common\components\Cache;
use common\components\StoreManager;
use yii\helpers\Html;

class Address extends \common\models\db\Address
{
    const TYPE_PRIMARY = 'primary';
    const TYPE_SHIPPING = 'shipping';

    const IS_DEFAULT = 1;
    public static function FindbyCustomerId($customerId = null, $cache = false)
    {
        $key = 'CACHE_ADDRESS_BY_CUSTOMER_ID_' . $customerId;
        $data = Cache::get($key);
        if (!$data || $customerId == null || $cache == false) {
            $data = self::find()->where(['customer_id' => $customerId])->orderBy(['id' => SORT_DESC])->asArray()->all();
            Cache::set($key, $data, 60 * 60);
        }
        return $data;
    }
    public function save($runValidation = true, $attributeNames = null)
    {
        $this->last_name = Html::encode($this->last_name);
        $this->first_name = Html::encode($this->first_name);
        $this->address = Html::encode($this->address);
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
    public function validateAddress(){
        $error_list = [];
        if(!$this->first_name){
            $error_list['first_name'] = \Yii::t('frontend','First name invalid');
        }
        if(!$this->phone){
            $error_list['phone'] = \Yii::t('frontend','Phone invalid');
        }
        if(!$this->email){
            $error_list['email'] = \Yii::t('frontend','Email invalid');
        }
        if(!$this->province_id){
            $error_list['province_id'] = \Yii::t('frontend','Province invalid');
        }
        if(!$this->district_id){
            $error_list['district_id'] = \Yii::t('frontend','District invalid');
        }
        if(!$this->customer_id){
            $error_list['customer_id'] = \Yii::t('frontend','Customer Id invalid');
        }
        if(!$this->address){
            $error_list['address'] = \Yii::t('frontend','Address invalid');
        }
        if(!$this->post_code && $this->store_id == StoreManager::STORE_ID){
            $error_list['post_code'] = \Yii::t('frontend','Zip code invalid');
        }
        return $error_list;
    }
    public static function creatAdress($address, $id_customer = null)
    {
        if (isset($address['receiverAddressId']) && $address['receiverAddressId'] > 0) {
            $model = self::findOne($address['receiverAddressId']);
        } else {
            $model = new self();
        }
        $model->first_name = $address['receiverName'];
        $model->email = $address['receiverEmail'];
        $model->country_id = $address['receiverCountryId'];
        $model->province_id = $address['receiverCityId'];
        $model->district_id = $address['receiverDistrictId'];
        $model->address = $address['receiverAddress'];
        $model->phone = $address['receiverPhone'];
        $model->customer_id = $id_customer;
        $model->save(false);
    }

    public static function getById($id, $cache = true)
    {
        $key = 'CACHE_ADDRESS_BY_ID_' . $id;
        $data = Cache::get($key);
        if (!$data || $id == null || $cache == false) {
            $data = Address::find()->where(['id' => $id])->one();
            Cache::set($key, $data, 60 * 60 * 24);
        }
        return $data;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $keys = [
            'CACHE_ADDRESS_BY_CUSTOMER_ID_' . $this->customer_id,
            'CACHE_ADDRESS_BY_ID_' . $this->id
        ];
        foreach ($keys as $key=>$value){
            Cache::delete($value);
        }
    }

}