<?php
/**
 * Created by PhpStorm.
 * User: galat
 * Date: 25/02/2019
 * Time: 16:48
 */

namespace common\models;


use yii\helpers\ArrayHelper;

class Address extends \common\models\db\Address
{
    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors = ArrayHelper::merge($behaviors, [
            'timestamp' => [
                'class' => \yii\behaviors\TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => time(),
            ],
        ]);
        return $behaviors;
    }
    public static function updateAll($attributes, $condition = '', $params = [])
    {
        $attributes = ArrayHelper::merge($attributes,['updated_at' => time()]);
        return parent::updateAll($attributes, $condition, $params); // TODO: Change the autogenerated stub
    }
}