<?php
return [
    1 => 17, //	WATCH
    2 => 25, //	CAMERA_AND_CAMERA_LENSES
    3 => 25, //	CAMERA
    4 => 25, //	CAMERA_LENSES
    5 => 57, //	PHONE
    6 => 57, //	CELL_PHONE
    7 => 58, //	OTHER_PHONE
    8 => 62, //	LAPTOP
    9 => 62, //	APPLE_ALIEN_WARE
    10 => 62, //	OTHER_LAPTOP
    11 => 29, //	SPEAKER_AMPLY
    12 => 29, //	ELECTRONICS
    13 => 61, //	IPOD
    14 => 64, //	DANGEROUS_GOODS
    15 => 39, //	DJ_GOODS
    16 => 51, //	GOLF_CLUBS
    17 => 21, //	MONITORS
    18 => 59, //	TABLET
    19 => 59, //	IPAD
    20 => 40, //	Headphone
    21 => 1, //	device golf,bida,tennis,badminton,fishing ...
    22 => 1, //	Phone / Cellphone parts & accessories
    23 => 1, //	Telescope / Binocular
    24 => 1, //	Kindle Amazon, Nook, e - Reader
    25 => 1, //	Tablet
    26 => 1, //	iPod
    27 => 1, //	Laptop
    28 => 1, //	Desktop CPU
    29 => 1, //	PC - SERVER
    30 => 1, //	Monitor
    31 => 1, //	Computer part, Mouse, Webcam, Keyboard
    32 => 1, //	Hard drive, Mainboard, Video card
    33 => 1, //	Internet Router
    34 => 1, //	RAM
    35 => 1, //	Printer
    36 => 1, //	Digital camera
    37 => 1, //	Camera lens
    38 => 1, //	Headphone
    39 => 1, //	Home theater system
    40 => 1, //	Amplifier & Receiver
    41 => 1, //	speakers
    42 => 1, //	DVD_CD_VCD player
    43 => 1, //	 Kim dictionary
    44 => 1, //	 Water purifier
    45 => 1, //	 Massage machine
    46 => 1, //	 Other electronics and household appliances
    47 => 1, //	Kitchenware
    48 => 1, //	Xbox_PS3_PS2_Wii
    49 => 1, //	PSP_Nintendo DS_3DS
    50 => 1, //	Watch
    51 => 1, //	Shoes
    52 => 1, //	Hand bag
    53 => 1, //	Glasses
    54 => 1, //	Cosmetics
    55 => 1, //	Perfume
    56 => 1, //	Personal care - Shampoo_Shower gel_Lotion
    57 => 1, //	Motor Parts
    58 => 1, //	Tool supplies
    59 => 1, //	 Golf sticks_billiards_ tennis rackets_badminton rackets_fishing rods
    60 => 1, //	Xe_dap
    61 => 1, //	 Guita_ saxophone_drum
    62 => 1, //	 Electric guitar_organ_piano
    63 => 1, //	 VCD_CD_cassette tape_plastic film disc
    64 => 1, //	 Clock to antique table
    65 => 1, //	 Book_ newspapers_magazines
    66 => 1, //	Zippo
    67 => 1, //	 Powdered milk
    68 => 1, // - Toys - Electrical toys
    69 => 1, //	 Breast pump
    70 => 1, //	Candy
    71 => 1, //	Tablet
    72 => 1, //	Kindle Amazon, Nook, e - Reader
    73 => 1, //	Kindle Amazon, Nook, e - Reader
    74 => 1, //	Kindle Amazon, Nook, e - Reader
    75 => 1, //	iPhone
    76 => 1, //	Internet Router
    77 => 1, //	OPTICAL_INSTRUMENT
    79 => 1, //	OFFICE_MACHINE
];