<?php
/**
 * Created by PhpStorm.
 * User: galat
 * Date: 06/03/2019
 * Time: 17:02
 */

namespace common\models;


class Manifest extends  \common\models\db\Manifest
{
    public function rules()
    {
        $paren = parent::rules();
        $child = [
            ['active', 'default', 'value' => self::STATUS_ACTIVE],
            ['active', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
        return array_merge($paren,$child); // TODO: Change the autogenerated stub
    }
}