<?php
/**
 * Created by PhpStorm.
 * User: galat
 * Date: 07/03/2019
 * Time: 10:41
 */

namespace common\models;

/**
 * Class Shipment
 * @package common\models
 * @property PackageItem[] $packageItems
 */

class Shipment extends \common\models\db\Shipment
{
    const STATUS_REMOVE_SHIPMENT = "REMOVED";
    const STATUS_NEW = "NEW";
    const STATUS_LOCAL_INSPECT_DONE = "LOCAL_INSPECT_DONE";

    public function rules()
    {
        $paren = parent::rules();
        $child = [
            [['warehouse_send_id', 'customer_id', 'receiver_email', 'receiver_name', 'receiver_phone', 'receiver_address', 'receiver_country_id', 'receiver_province_id', 'receiver_district_id'], 'required'],
        ];
        return array_merge($paren,$child); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $this->created_at = time();
        }
        $this->updated_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPackageItems()
    {
        return $this->hasMany(PackageItem::className(), ['shipment_id' => 'id']);
    }
}