<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2018-08-21
 * Time: 09:39
 */

namespace common\models\cms;


class WsPageItem extends \common\models\db_cms\WsPageItem
{

    const BLOCK5 = 'BLOCK5';
    const BLOCK_CONTENT = 'BLOCK_CONTENT';
    const BLOCK7 = 'BLOCK7';
    const BLOCK8 = 'BLOCK8';
    const LANDING = 'LANDING';
    const IMG5 = 'IMG5';
    const IMG7 = 'IMG7';
    const BRAND_SLIDER = 'BRAND_SLIDER';
    const LANDING_IMG_GIRD = 'LANDING_IMG_GIRD';
    const LANDING_IMG_FLUID = 'LANDING_IMG_FLUID';
    const LANDING_IMG_LIST = 'LANDING_IMG_LIST';
    const LANDING_SLIDE_FLUID = 'LANDING_SLIDE_FLUID';
    const LANDING_PRODUCT_CAROUSEL = 'LANDING_PRODUCT_CAROUSEL';
    const LANDING_PRODUCT_CAROUSEL_THUMB_NAILS = 'LANDING_PRODUCT_CAROUSEL_THUMB_NAILS';
    const LANDING_PRODUCT_BANNER_CENTER = 'LANDING_PRODUCT_BANNER_CENTER';
    const LANDING_BRAND_SLIDER = 'LANDING_BRAND_SLIDER';

    // NEW LANDING JUNE
    const JUN_LANDING_4_IMG_2_ROW = 'JUN_LANDING_4_IMG_2_ROW';
    const JUN_LANDING_3_IMG_1_ROW = 'JUN_LANDING_3_IMG_1_ROW';
    const JUN_LANDING_4_IMG_1_ROW = 'JUN_LANDING_4_IMG_1_ROW';
    const JUN_LANDING_6_IMG_1_ROW = 'JUN_LANDING_6_IMG_1_ROW';
    const JUN_LANDING_5_IMG_2_ROW_1_BIG = 'JUN_LANDING_5_IMG_2_ROW_1_BIG';
    const JUN_LANDING_5_IMG_2_ROW_1_BANNER = 'JUN_LANDING_5_IMG_2_ROW_1_BANNER';
    CONST JUN_LANDING_7_IMG_2_ROW = 'JUN_LANDING_7_IMG_2_ROW';
    const UK_REQUEST_CALCULATE = 'UK_REQUEST_CALCULATE';

    const TYPE_LANDING = 'LANDING';
    const TYPE_BLOCK = 'BLOCK';
    const TYPE_CATEGORY = "CATEGORY";
    const TYPE_SLIDER = "SLIDER";
    const TYPE_ALIAS = "ALIAS";
}