<?php
namespace wallet\modules\v1\models\enu;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use common\components\Language;

/**
 * Created by PhpStorm.
 * User: quangquyet
 * Date: 14/05/2018
 * Time: 11:59
 */
class ResponseCode
{

    const SUCCESS ='0000';
    const ERROR = '1000';
    const AMOUNT_TRANSFER_FAILED = '1303';
    const INVALID = '1303';
    const NOT_FOUND = '1404';


    //Refund form validate
    const REFUND_TOTAL_AMOUNT_MIN ='4001';
    const REFUND_TOTAL_AMOUNT_NULL ='4002';
    const REFUND_MERCHAIN_ID_NULL ='4003';
    const REFUND_NOTE_NULL ='4004';
    const REFUND_TOTAL_AMOUNT_MAX ='4005';
    const REFUND_TOTAL_AMOUNT_NOT_INTERGER ='4006';
    const REFUND_TRANSACTION_DUPLICATE ='4007';

    const WALLET_TRANSACTION_SUCCESS = '0000';
    const WALLET_TRANSACTION_FAIL = '1001';
    const WALLET_PAYMENT_TRANS_NOT_FOUND = '1002';
    const WALLET_TRANS_NOT_FOUND = '1003';
    const WALLET_TRANSACTION_NOT_FOUND = '1004';
    const WALLET_TRANSACTION_INVALID_MERCHANT_REQUIRED = '1100';
    const WALLET_TRANSACTION_INVALID_MERCHANT_INTEGER = '1105';
    const WALLET_TRANSACTION_INVALID_AMOUNT_REQUIRED = '1104';
    const WALLET_TRANSACTION_INVALID_TOTAL_AMOUNT_INTEGER = '1105';
    const WALLET_TRANSACTION_INVALID_TOTAL_AMOUNT_GTE = '1106';
    const WALLET_TRANSACTION_INVALID_PROMOTION_AMOUNT_INTEGER = '1107';
    const WALLET_TRANSACTION_INVALID_CODE_REQUIRED = '1108';
    const WALLET_TRANSACTION_INVALID_CODE_STRING = '1109';
    const WALLET_TRANSACTION_INVALID_PAYMENT_METHOD_REQUIRED = '1010';
    const WALLET_TRANSACTION_INVALID_PAYMENT_METHOD_STRING = '1010';
    const WALLET_TRANSACTION_INVALID_PAYMENT_PROVIDER_REQUIRED = '1011';
    const WALLET_TRANSACTION_INVALID_PAYMENT_PROVIDER_STRING = '1011';
    const WALLET_TRANSACTION_INVALID_BANK_CODE_STRING = '1012';
    const WALLET_TRANSACTION_INVALID_TYPE_REQUIRED  = '1013';
    const WALLET_TRANSACTION_INVALID_TYPE_NOT_EXIST = '1013';
    const WALLET_TRANSACTION_INVALID_OTP_RECEIVE_NOT_EXIST = '1013';
    const WALLET_TRANSACTION_INVALID_VERIFY_RECEIVE_REQUIRED = '1013';
    const PAYMENT_SUCCESS='000';

}