<?php
namespace common\logs;

use common\models\User;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class TrackingLogs extends \common\modelsMongo\TrackingLogs
{
    const TRACKING_CREATE = 'CREATE';
    const TRACKING_UPDATE = 'UPDATE';
    const TRACKING_MAP_PRODUCT = 'MAP_PRODUCT';
    const TRACKING_MERGE_TRACKING_WAST = 'MERGE_TRACKING_WAST';
    const TRACKING_MERGE_TRACKING_SELLER = 'MERGE_TRACKING_SELLER';
    const TRACKING_MERGE_PACKAGE = 'MERGE_PACKAGE';
    const TRACKING_REMOVE = 'REMOVE';

    const STATUS_SELLER_SHIPPED = 'SELLER_SHIPPED';
    const STATUS_STOCK_IN_US = 'STOCK_IN_US';
    const STATUS_STOCK_OUT_US = 'STOCK_OUT_US';
    const STATUS_STOCK_IN_LOCAL = 'STOCK_IN_LOCAL';
    const STATUS_STOCK_OUT_LOCAL = 'STOCK_OUT_LOCAL';
    const STATUS_DELIVERY = 'STOCK_DELIVERY';
    public function save($runValidation = true, $attributeNames = null)
    {
        try{
            $this->created_at = date('Y-m-d H:i:s');
            $this->user_name = 'guest';
            /** @var User $user */
            $user = \Yii::$app->user->getIdentity();
            if($user){
                $this->user_name = $user->username;
                $this->user_id = $user->id;
                $this->user_email = $user->email;
            }
            return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        }catch (\Exception $exception){
            \Yii::debug($exception);
            //Todo save to file if mongo error.
//            $fileDirPath = 'file/tracking_logs';
//            if (!file_exists($fileDirPath)) {
//                @mkdir($fileDirPath, 0777, true);
//            }
//            $writer = new Xlsx($spreadsheet);
//            $writer->save($fileName);
            return false;
        }
    }
    public static function GetLogTracking($code){
        $rs = [];
        if($code){
            /** @var self[] $data */
            $data = self::find()->where(['like','tracking_code',$code])->orderBy('created_at desc')->all();
            \Yii::debug($data);
            foreach ($data as $datum){
                \Yii::debug($datum->created_at);
                $tmp = new LogViewForm();
                $tmp->create_time = $datum->created_at;
                $tmp->type_log = $datum->getTypeLogText();
                $tmp->user_email = $datum->user_email;
                $tmp->user_name = $datum->user_name;
                $tmp->message = $datum->message_log;
                $tmp->code_reference = $datum->getCodeReferent();
                $rs[] = $tmp->getAttributes();
            }
        }
        return $rs;
    }
    public function getCodeReferent(){
        switch ($this->type_log){
            case self::TRACKING_MERGE_TRACKING_WAST:
            case self::TRACKING_MERGE_TRACKING_SELLER:
            case self::TRACKING_REMOVE:
                return 'Tracking: '. $this->tracking_code_reference;
                break;
            case self::TRACKING_MERGE_PACKAGE:
                return 'Package: '.$this->package_code;
                break;
            case self::TRACKING_MAP_PRODUCT:
                return 'Product: '.$this->product_id;
                break;
            default:
                return '';
                break;
        }
    }
    public function getTypeLogText(){
        switch ($this->type_log){
            case self::TRACKING_MERGE_TRACKING_WAST:
                return 'Gộp hàng thừa';
                break;
            case self::TRACKING_MERGE_TRACKING_SELLER:
                return 'Gộp tracking seller';
                break;
            case self::TRACKING_REMOVE:
                return 'Xoá';
                break;
            case self::TRACKING_MERGE_PACKAGE:
                return 'Đưa vào kiện';
                break;
            case self::TRACKING_MAP_PRODUCT:
                return 'Map product';
                break;
            case self::TRACKING_CREATE:
                return 'Tạo mới';
                break;
            case self::TRACKING_UPDATE:
                return 'Cập nhật';
                break;
            default:
                return '';
                break;
        }
    }
}