<?php


namespace frontend\assets;

use Yii;
use yii\helpers\Json;
use yii\web\AssetBundle;
use yii\web\View;

class WeshopAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public $js = [
        'js/ws.js',
        'js/ws.browse.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap4\BootstrapAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    protected function getClientOptions()
    {
        return [
            'currency' => 'VND',
            'priceDecimal' => 0,
            'pricePrecision' => -3,
        ];
    }

    public function registerAssetFiles($view)
    {
        parent::registerAssetFiles($view);
        $options = Json::htmlEncode($this->getClientOptions());
        $view->registerJs("console.log($options);");
    }
}