<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-03-06
 * Time: 08:44
 */

namespace api\modules\v1\controllers;


use api\controllers\BaseApiController;
use api\modules\v1\api\models\ProductDetailFrom;
use Yii;

class ProductController extends BaseApiController
{

    /**
     * @inheritdoc
     * @return array
     */
    public function verbs()
    {
        return parent::verbs(); // TODO: Change the autogenerated stub
    }

    public function actionDetail()
    {
        $paramRequests = Yii::$app->getRequest()->getBodyParams();
        $form = new ProductDetailFrom();
        if (!isset($paramRequests['type'])) {
            return $this->response(false, "missing parameter `type`");
        }
        if (($type = $paramRequests['type']) === null || $type === '' || !in_array($type, ['ebay', 'amazon', 'amazon-jp'])) {
            return $this->response(false, "parameter `type` ether `ebay`, `amazon` or `amazon-jp`");
        }
        unset($paramRequests['type']);
        $type = strtolower($type);
        $form->setScenario($type);
        $form->load($paramRequests,'');
        if(($res = $form->detail()) === false){
            return $this->response(false, $form->getFirstErrors());
        }
        return $this->response(true,"get detail success",$res);
    }
}