<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-03-06
 * Time: 08:44
 */

namespace api\modules\v1\controllers;


use api\controllers\BaseApiController;
use api\modules\v1\models\ProductDetailFrom;
use common\products\BaseProduct;
use Yii;

class ProductController extends BaseApiController
{

    /**
     * @inheritdoc
     * @return array
     */
    public function verbs()
    {
        return parent::verbs(); // TODO: Change the autogenerated stub
    }

    public function actionDetail()
    {
        $paramRequests = Yii::$app->getRequest()->getBodyParams();
        $form = new ProductDetailFrom();
        $form->load($paramRequests, '');
        /** @var $product false | BaseProduct */
        if (($product = $form->detail()) === false) {
            return $this->response(false, $form->getFirstErrors());
        }
        return $this->response(true, "get detail success", $product);
    }

    public function actionSearch()
    {

    }

    public function actionCalculator(){
        $paramRequests = Yii::$app->getRequest()->getQueryParam();
        $form = new ProductDetailFrom();
        $form->load($paramRequests, '');
        /** @var $product false | BaseProduct */
        if (($product= $form->detail()) === false) {
            return $this->response(false, $form->getFirstErrors());
        }
        $data = [
            'type' => $product->type,
            ''
        ];
        return $this->response(true, "get detail success", $res->getAdditionalFees());
    }
}