<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-03-06
 * Time: 08:44
 */

namespace api\modules\v1\controllers;


use api\controllers\BaseApiController;
use api\modules\v1\models\ProductDetailFrom;
use Yii;

class ProductController extends BaseApiController
{

    /**
     * @inheritdoc
     * @return array
     */
    public function verbs()
    {
        return parent::verbs(); // TODO: Change the autogenerated stub
    }

    public function actionDetail()
    {
        $paramRequests = Yii::$app->getRequest()->getBodyParams();
        $form = new ProductDetailFrom();
        $form->load($paramRequests,'');
        if(($res = $form->detail()) === false){
            return $this->response(false, $form->getFirstErrors());
        }
        return $this->response(true,"get detail success",$res->getAdditionalFees());
    }
}