<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Seller.proto

namespace GPBMetadata\Proto;

class Seller
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a1270726f746f2f53656c6c65722e70726f746f120653656c6c65" .
            "7222250a145773437265617465436168696e52657175657374120d0a0550" .
            "6172616d18012001280922580a155773437265617465436168696e526573" .
            "706f6e7365120d0a054572726f72180120012808120f0a074d6573736167" .
            "6518022001280912110a094572726f72436f6465180320012809120c0a04" .
            "44617461180420012809325f0a0d53656c6c657253657276696365124e0a" .
            "0d5773437265617465436168696e121c2e53656c6c65722e577343726561" .
            "7465436168696e526571756573741a1d2e53656c6c65722e577343726561" .
            "7465436168696e526573706f6e736522004209a2020363616cd002016206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

