<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-02-27
 * Time: 17:17
 */

namespace api\controllers;

use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpHeaderAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;


class BaseApiController extends \yii\rest\Controller
{

    public $serializer = 'common\components\rest\WeshopSerializer';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                'httpBearer' => [
                    'class' => HttpBearerAuth::className()
                ],
                'weshopApi' => [
                    'class' => \common\components\rest\WeshopApiAuth::className()
                ],
                'httpHeader' => [
                    'class' => HttpHeaderAuth::className(),
                    'header' => 'X-Access-Token'
                ],
                'queryParam' => [
                    'class' => QueryParamAuth::className(),
                ]

            ],
        ];
        return $behaviors;
    }

    public function verbs()
    {
        return parent::verbs(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        return array_merge(parent::actions(),[
            'options' => [
                'class' => 'yii\rest\OptionsAction',
            ],
        ]);
    }
}