<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-02-27
 * Time: 17:17
 */

namespace api\controllers;

use common\helpers\WeshopHelper;
use Yii;
use yii\filters\AccessControl;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\HttpHeaderAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\Cors;
use yii\web\Request;
use yii\web\Response;

class BaseApiController extends \yii\rest\Controller
{

    public $serializer = 'common\rest\Serializer';

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        // remove authentication filter
        if (isset($behaviors['authenticator'])) {
            unset($behaviors['authenticator']);
        }
        $behaviors['corsFilter'] = [
            'class' => Cors::className(),
        ];
        // re-add authentication filter
        $behaviors['authenticator']['except'] = ['options'];
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'except' => ['options'], // avoid authentication on CORS-pre-flight requests (HTTP OPTIONS method)
            'authMethods' => [
                'httpBearer' => [
                    'class' => HttpBearerAuth::className()
                ],
                'weshopApi' => [
                    'class' => \common\rest\WeshopAuth::className()
                ],
                'httpHeader' => [
                    'class' => HttpHeaderAuth::className(),
                    'header' => 'X-Access-Token'
                ],
                'queryParam' => [
                    'class' => QueryParamAuth::className(),
                ]

            ],
        ];
        $behaviors['accessControl'] = [
            'class' => AccessControl::className(),
            'rules' => $this->rules(),
            'denyCallback' => function ($rule, $action) {
                Yii::info($action);
                throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
            }
        ];
        return $behaviors;
    }

    /**
     * Declares the allowed HTTP verbs.
     * Please refer to [[VerbFilter::actions]] on how to declare the allowed verbs.
     * @return array the allowed HTTP verbs.
     */
    public function verbs()
    {
        return parent::verbs(); // TODO: Change the autogenerated stub
    }

    /**
     * Declares the allowed access rule.
     * @return array
     */
    public function rules()
    {
        return [
            [
                'allow' => true,
                'roles' => ['@'],
            ],
        ];
    }

    /**
     * @return array
     */
    public function actions()
    {
        return array_merge(parent::actions(), [
            'options' => [
                'class' => 'yii\rest\OptionsAction',
            ],
        ]);
    }

    public function init()
    {
        parent::init();
        Yii::configure(Yii::$app, [
            'components' => [
                'request' => [
                    'class' => Request::className(),
                    'enableCookieValidation' => false,
                    'enableCsrfCookie' => false,
                    'parsers' => [
                        'application/json' => 'yii\web\JsonParser',
                    ]
                ],
                'response' => [
                    'class' => Response::className(),
                    'format' => Response::FORMAT_JSON,
                    'formatters' => [
                        Response::FORMAT_JSON => [
                            'class' => 'yii\web\JsonResponseFormatter',
                            'prettyPrint' => true, // use "pretty" output in debug mode
                        ],
                    ],
                ]
            ]
        ]);
    }

    public function afterAction($action, $result)
    {
        $result = parent::afterAction($action, $result);
        \Yii::info($result, $action->id);
        return $result;
    }

    /**
     * @param bool $success
     * @param string $message
     * @param array $data
     * @return array
     */
    public function response($success = true, $message = 'Ok', $data = [])
    {
        return WeshopHelper::response($success, $message, $data);
    }

    /**
     * @param bool $keyOnly
     * @param array $exception
     * @return array
     */
    public function getAllRoles($keyOnly = false, $exception = [])
    {
        if (is_string($exception)) {
            $exception = [$exception];
        }
        $roles = [];
        foreach ((array)Yii::$app->getAuthManager()->getRoles() as $name => $role) {
            if (in_array($name, $exception)) {
                continue;
            }
            if ($keyOnly) {
                $roles[] = $name;
            } else {
                $roles[$name] = $role;
            }
        }
        return $roles;

    }

    /**
     * @param $permissionName
     * @param array $params
     * @return bool
     * @throws \yii\web\ForbiddenHttpException
     */
    public function can($permissionName, $params = []){
        if(Yii::$app->getUser()->can($permissionName, $params,true)){
            return true;
        }
        throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
    }
}