<?php
/**
 * Created by PhpStorm.
 * User: galat
 * Date: 28/03/2019
 * Time: 11:34 SA
 */

namespace api\controllers;


use yii\base\Controller;

class TestController extends Controller
{
    public function actionGetCustomFee()
    {

        return parent::actions(); // TODO: Change the autogenerated stub
    }
}
