<?php

namespace frontend\modules\favorites\models;

use frontend\modules\favorites\Favorite as BaseFavorite;

/**
 * This is the model class for table "favorites".
 */
class Favorite extends BaseFavorite
{

    /*
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->obj_type = @unserialize($this->obj_type);
    }
    */
}
