<?php
namespace common\request;
use Yii;
use yii\web\Request;

class UUID extends Request
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public $UUID;

    public  function setUuid($uuid)
    {
        return $this->UUID = $uuid;
    }


}
