<?php

/**
 * Created by PhpStorm.
 * User: quangquyet
 * Date: 10/05/2018
 * Time: 10:00
 */

namespace common\payment\providers\wallet;

use common\models\Customer;
use Yii;
use Exception;
use yii\base\BaseObject;
use yii\httpclient\Client;


class WalletService extends BaseObject
{
    const MERCHANT_IP_PRO = 1;
    const MERCHANT_IP_DEV = 4;
    const WITHDRAW_MIN_AMOUNT = 10000;
    const TYPE_TOP_UP = 'TOP_UP';
    const TYPE_FREEZE = 'FREEZE';
    const TYPE_UN_FREEZE = 'UN_FREEZE';
    const TYPE_PAY_ORDER = 'PAY_ORDER';
    const TYPE_REFUND = 'REFUND';
    const TYPE_WITH_DRAW = 'WITH_DRAW';

    const STATUS_QUEUE = 0;
    const STATUS_PROCESSING = 1;
    const STATUS_COMPLETE = 2;
    const STATUS_CANCEL = 3;
    const STATUS_FAIL = 4;

    public $user;
    public $merchant_id;
    public $type;
    public $transaction_code;
    public $total_amount;
    public $payment_method;
    public $payment_provider;
    public $bank_code;
    public $payment_transaction;

    public $otp_type;
    public $otp_code;
    /**
     * @var WalletClient
     */
    private $_walletClient;

    public function getWalletClient()
    {
        if (!is_object($this->_walletClient)) {
            $this->_walletClient = Yii::$app->authClientCollection->getClient('wallet');
        }
        return $this->_walletClient;
    }

    public function isGuest()
    {
        return Yii::$app->getSession()->get('wallet_token') === null;
    }

    public function login($password)
    {
        /** @var  $user Customer */
        $user = Yii::$app->user->identity;

        $walletClient = $this->getWalletClient();
        try {
            $walletClient->authenticateUser($user->username, $password);
            return true;
        } catch (Exception $exception) {
            $client = new Client([
                'baseUrl' => $walletClient->apiBaseUrl
            ]);
            $request = $client->createRequest();
            $request->setUrl('wallet-no-auth/create-wallet');
            $request->setMethod('POST');
            $request->setData(['customer' => $user->getAttributes()]);
            $response = $client->send($request);
            if ($response->isOk) {
                $response = $response->getData();
                if ($response['success']) {
                    try {
                        $walletClient->authenticateUser($user->username, Yii::$app->request->post('password'));
                        return true;
                    } catch (Exception $e) {
                        return false;
                    }

                }
            }
            return false;
        }
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function topUpTransaction()
    {
        $data = [];
        $data['amount_total'] = $this->total_amount;
        $data['method'] = $this->payment_method;
        $data['payment_provider'] = $this->payment_provider;
        $data['bank_code'] = $this->bank_code;
        $data['merchant_id'] = @self::MERCHANT_IP_PRO;

        $client = $this->getWalletClient();
        $uses = $client->getAccessToken()->getParams();
        $wallet_client_id = ($uses['user']['id']);

        if (in_array($wallet_client_id, [1, 3])) {
            $data['merchant_id'] = @self::MERCHANT_IP_DEV;
        }
        $rs = $client->createApiRequest()
            ->setMethod('POST')
            ->setUrl('topup/create')
            ->setData($data)->send()->getData();
        return $rs['data']['wallet_transaction_code']['data']['code'];
    }

    public function pushToTopUp()
    {
        $data['wallet_transaction_code'] = $this->transaction_code;
        $data['payment_transaction'] = $this->payment_transaction;
        $data['time'] = date('Y-m-d H:i:s');
        $client = $this->getWalletClient();
        $rs = $client->createApiRequest()
            ->setMethod('POST')
            ->setUrl('topup/pushtotopup')
            ->setData($data)->send()->getData();
        return $rs;
    }

    public function pushToTopUpNoAuth()
    {
        $data['wallet_transaction_code'] = $this->transaction_code;
        $data['payment_transaction'] = $this->payment_transaction;
        $data['time'] = date('Y-m-d H:i:s');
        $wlClient = $this->getWalletClient();
        $client = new Client([
            'baseUrl' => $wlClient->apiBaseUrl
        ]);
        $rs = $client->createRequest()
            ->setMethod('POST')
            ->setUrl('wallet-no-auth/push-to-top-up')
            ->setData($data)->send()->getData();
        return $rs;
    }

    public function getTopUpTransaction()
    {
        $data['wallet_transaction_code'] = $this->transaction_code;

        $client = $this->getWalletClient();
        $rs = $client->createApiRequest()
            ->setMethod('POST')
            ->setUrl('topup/gettransaction')
            ->setData($data)
            ->send()
            ->getData();
        return $rs;
    }


    public function listTransaction($filter = null, $limit = 20, $offset = 0)
    {
        $data['limit'] = $limit;
        $data['offset'] = $offset;

        if ($filter) {
            $data['filter'] = json_encode($filter);
        }

        $client = $this->getWalletClient();
        $rs = $client->createApiRequest()
            ->setMethod('POST')
            ->setUrl('transaction/index')
            ->setData($data)
            ->send()
            ->getData();
        return $rs;
    }

    public function detailWalletClient()
    {
        $data = [];
        $client = $this->getWalletClient();
        $rs = $client->createApiRequest()
            ->setMethod('POST')
            ->setUrl('clients/detail')
            ->setData($data)
            ->send()
            ->getData();
        return $rs;
    }


    public function cancelTopUpTransaction()
    {
        $data['wallet_transaction_code'] = $this->transaction_code;

        $client = $this->getWalletClient();
        $rs = $client->createApiRequest()
            ->setMethod('POST')
            ->setUrl('topup/canceltransaction')
            ->setData($data)
            ->send()
            ->getData();

        return $rs;
    }

    public function createPaymentTransaction()
    {
        $data['merchant_id'] = $this->merchant_id;
        $data['transaction_code'] = $this->payment_transaction;
        $data['total_amount'] = $this->total_amount;
        $data['payment_method'] = $this->payment_provider;
        $data['payment_provider'] = $this->payment_provider;
        $data['bank_code'] = $this->bank_code;
        $data['otp_receive_type'] = $this->otp_type;
        $request = $this->getWalletClient()->createApiRequest()
            ->setMethod('post')
            ->setFormat('json')
            ->setUrl('transaction/create')
            ->setData($data);
        $response = $request->send();
        return $response->getData();
    }

    public function validateOtp()
    {
        $requestApi = $this->getWalletClient()->createApiRequest();
        $requestApi->setMethod('POST');
        $requestApi->setUrl('transaction/verify-opt');
        $requestApi->setData([
            'transaction_code' => $this->transaction_code,
            'otp_code' => $this->otp_code
        ]);
        $responseApi = $requestApi->send();
        return $responseApi->getData();
    }

    public function refreshOtp()
    {
        $requestWalletApi = $this->walletClient->createApiRequest();
        $requestWalletApi->setMethod('POST');
        $requestWalletApi->setUrl('transaction/refresh-otp');
        $requestWalletApi->setData([
            'transaction_code' => $this->transaction_code,
            'otp_receive_type' => $this->otp_type,
        ]);
        $responseWalletApi = $requestWalletApi->send();
        return $responseWalletApi->getData();
    }

}