<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Seller.proto

namespace Seller;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Seller.CreateShipmentRequest</code>
 */
class CreateShipmentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Ma Quoc Gia
     *
     * Generated from protobuf field <code>string Country = 1;</code>
     */
    private $Country = '';
    /**
     * User id
     *
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     */
    private $UserId = 0;
    /**
     * Nguon tao (weshop : 2)
     *
     * Generated from protobuf field <code>int32 Source = 3;</code>
     */
    private $Source = 0;
    /**
     * chuoi json dumps
     *
     * Generated from protobuf field <code>string Param = 4;</code>
     */
    private $Param = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Country
     *           Ma Quoc Gia
     *     @type int $UserId
     *           User id
     *     @type int $Source
     *           Nguon tao (weshop : 2)
     *     @type string $Param
     *           chuoi json dumps
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Seller::initOnce();
        parent::__construct($data);
    }

    /**
     * Ma Quoc Gia
     *
     * Generated from protobuf field <code>string Country = 1;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->Country;
    }

    /**
     * Ma Quoc Gia
     *
     * Generated from protobuf field <code>string Country = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->Country = $var;

        return $this;
    }

    /**
     * User id
     *
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * User id
     *
     * Generated from protobuf field <code>int32 UserId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->UserId = $var;

        return $this;
    }

    /**
     * Nguon tao (weshop : 2)
     *
     * Generated from protobuf field <code>int32 Source = 3;</code>
     * @return int
     */
    public function getSource()
    {
        return $this->Source;
    }

    /**
     * Nguon tao (weshop : 2)
     *
     * Generated from protobuf field <code>int32 Source = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkInt32($var);
        $this->Source = $var;

        return $this;
    }

    /**
     * chuoi json dumps
     *
     * Generated from protobuf field <code>string Param = 4;</code>
     * @return string
     */
    public function getParam()
    {
        return $this->Param;
    }

    /**
     * chuoi json dumps
     *
     * Generated from protobuf field <code>string Param = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->Param = $var;

        return $this;
    }

}

