<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Seller.proto

namespace Seller;

/**
 * Protobuf type <code>Seller.SellerService</code>
 */
interface SellerServiceInterface
{
    /**
     * grpc create topup from weshop
     *
     * Method <code>wsCreateCahin</code>
     *
     * @param \Seller\WsCreateCahinRequest $request
     * @return \Seller\WsCreateCahinResponse
     */
    public function wsCreateCahin(\Seller\WsCreateCahinRequest $request);

    /**
     * Method <code>createShipment</code>
     *
     * @param \Seller\CreateShipmentRequest $request
     * @return \Seller\CreateShipmentResponse
     */
    public function createShipment(\Seller\CreateShipmentRequest $request);

    /**
     * Method <code>syncProduct</code>
     *
     * @param \Seller\SyncProductRequest $request
     * @return \Seller\SyncProductResponse
     */
    public function syncProduct(\Seller\SyncProductRequest $request);

}

