<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Seller.proto

namespace Seller;

/**
 * Protobuf type <code>Seller.SellerService</code>
 */
interface SellerServiceInterface
{
    /**
     * grpc create topup from weshop
     *
     * Method <code>wsCreateCahin</code>
     *
     * @param \Seller\WsCreateCahinRequest $request
     * @return \Seller\WsCreateCahinResponse
     */
    public function wsCreateCahin(\Seller\WsCreateCahinRequest $request);

}

