<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Seller.proto

namespace Seller;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Seller.SyncProductRequest</code>
 */
class SyncProductRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Data = 1;</code>
     */
    private $Data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Seller::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Data = 1;</code>
     * @return string
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>string Data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->Data = $var;

        return $this;
    }

}

