<?php


namespace console\controllers;


use common\components\boxme\BoxMeClient;
use common\models\Order;
use yii\console\Controller;

class PushOrderController extends Controller
{
    public function actionPushOrder($rows)
    {
        $this->stdout_F('Rows: '.$rows);
        $this->stdout_F('Bắt đầu chạy job: ');
        /** @var Order[] $orders */
        $orders = Order::find()
            ->where(['is not', 'tracking_codes', null])
            ->andWhere(['<>', 'tracking_codes', ''])
            ->andWhere(['or', ['order_boxme' => ''], ['is', 'order_boxme', null]])
            ->andWhere(['or', ['shipment_boxme' => ''], ['is', 'shipment_boxme', null]])
            ->limit($rows)->all();
        $this->stdout_F('Có '.count($orders).' orders sẽ được chạy');
        foreach ($orders as $order) {
            $this->stdout_F('Chạy đơn: '.$order->ordercode);
            $this->stdout_F('Bắt đầu sync product:... ');
            foreach ($order->products as $product) {
                $this->stdout_F('sync product: '.$product->sku.' - '.$product->parent_sku);
                $productBM = BoxMeClient::SyncProduct($product);
                print_r($productBM);
                $this->stdout_F('');
                if(is_array($productBM) && isset($productBM[0]) && !$productBM[0]){
                    $this->stdout_F('sync false.!');
                }else{
                    $this->stdout_F('sync success.!');
                }
            }
            $this->stdout_F('Tạo order box me: ...');
            $orderBM = BoxMeClient::CreateOrder($order);
            print_r($orderBM);
            if(!$orderBM || (is_array($orderBM) && !$orderBM[0] )){
                $this->stdout_F('Tạo order box me lỗi. Bỏ qua order.');
                $this->stdout_F('-------ERROR----------');
                continue;
            }
            $this->stdout_F('');
            $this->stdout_F('Tạo order box me success.');
            $trackingCodes = explode(',',$order->tracking_codes);
            if($trackingCodes && count($trackingCodes) > 0){
                $this->stdout_F('Tạo shipment box me: ...');
                foreach ($trackingCodes as $trackingCode){
                    $this->stdout_F('Tạo shipment box me cho tracking code: '.$trackingCode);
                    print_r(BoxMeClient::CreateLiveShipment($order,$trackingCode));
                    $this->stdout_F('');
                    $this->stdout_F('Tạo shipment box me success!');
                }
                $this->stdout_F('---------SUCCESS---------');
            }
        }
        $this->stdout_F('Job end ---------------------------');
    }
    public function stdout_F($string,$option = '')
    {

        return parent::stdout($string."\n",$option); // TODO: Change the autogenerated stub
    }
}