<?php
/**
 * Created by PhpStorm.
 * User: vinhs
 * Date: 2019-02-22
 * Time: 13:27
 */

namespace common\components\db;

class ActiveRecord extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $reflector = new \ReflectionClass($this);
        if($reflector->hasProperty('created_time') || $reflector->hasProperty('updated_time')){
            $behaviors['timestamp'] = [
                'class' => \yii\behaviors\TimestampBehavior::class,
                'createdAtAttribute' => $this->hasAttribute('created_time') ? 'created_time' : false,
                'updatedAtAttribute' => $this->hasAttribute('updated_time') ? 'updated_time' : false,
                'value' => new \yii\db\Expression('NOW()'),
            ];
        }
        if($reflector->hasProperty('created_by') || $reflector->hasProperty('updated_by')){
            $behaviors['timestamp'] = [
                'class' => \yii\behaviors\BlameableBehavior::class,
                'createdAtAttribute' => $this->hasAttribute('created_by') ? 'created_by' : false,
                'updatedAtAttribute' => $this->hasAttribute('updated_by') ? 'updated_by' : false,
                'value' => new \yii\db\Expression('NOW()'),
            ];
        }
        return $behaviors;
    }


    public function formName()
    {
        return parent::formName(); // TODO: Change the autogenerated stub
    }

    public function toArray(array $fields = [], array $expand = [], $recursive = true)
    {
        return parent::toArray($fields, $expand, $recursive);
    }
}