<?php

namespace frontend\modules\account\controllers;

use Yii;
use common\models\Order;
use userbackend\models\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends BaseAccountController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
    }

    protected function rules()
    {
        return [
            [
                'actions' => ['index'],
                'allow' => true
            ],
            [
                'actions' => ['index','order'],
                'allow' => true,
                'roles' => ['@'],
            ]
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $userId = Yii::$app->user->getId();
        $get = Yii::$app->request->get();
        $dataProvider = Order::find()
            ->with('products')
            ->where(['=', 'customer_id', $userId]);
        if (isset($get['status']) && !empty($get['status'])) {
            $dataProvider ->andWhere(['=','current_status', $get['status']]);
        }
        if (isset($get['purchase']) && !empty($get['purchase'])) {
            if ($get['purchase'] == 'paid') {
                $dataProvider ->andWhere([
                    'and',
                    ['>','total_paid_amount_local', 0],
                    ['IS NOT', 'total_paid_amount_local', null]
                ]);
            } if ($get['purchase'] == 'unpaid') {
                $dataProvider ->andWhere([
                    'or',
                    ['=','total_paid_amount_local', 0],
                    ['IS', 'total_paid_amount_local', null]
                ]);
            }
        }
        $models = $dataProvider->all();
        return $this->render('index', [
            'models' => $models,
//            'pages' => $pages
        ]);
    }

    public function actionView()
    {
        $orderCode = Yii::$app->request->get('orderCode');
        $model = Order::find()->with('products')->where(['ordercode' => $orderCode])->one();
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
