<?php


namespace frontend\modules\account\controllers;


use frontend\modules\payment\providers\wallet\WalletService;
use yii\helpers\ArrayHelper;

class WalletController extends BaseAccountController
{
    public function beforeAction($action)
    {
        $before = parent::beforeAction($action); // TODO: Change the autogenerated stub
        if(WalletService::isGuest()){
            return \Yii::$app->response->redirect('my-weshop/wallet.html');
        }else{
            return $before;
        }
    }

    public function actionIndex(){
        return $this->render('index');
    }
    public function actionTopUp(){
        return $this->render('top-up');
    }
    public function actionDetail($transaction_code){
        return $this->render('detail');
    }
    public function actionWithdraw(){
        return $this->render('withdraw');
    }
    public function actionHistory(){
        $walletS = new WalletService();
        $wallet = ArrayHelper::getValue($walletS->detailWalletClient(),'data');
        $listTransaction = ArrayHelper::getValue($walletS->listTransaction(),'data');
        return $this->render('history',[
            'wallet' => $wallet,
            'trans' => $listTransaction
        ]);
    }
}